Document: clubdistro
Title: Debian clubdistro Manual
Author: <insert document author here>
Abstract: This manual describes what clubdistro is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/clubdistro/clubdistro.sgml.gz

Format: postscript
Files: /usr/share/doc/clubdistro/clubdistro.ps.gz

Format: text
Files: /usr/share/doc/clubdistro/clubdistro.text.gz

Format: HTML
Index: /usr/share/doc/clubdistro/html/index.html
Files: /usr/share/doc/clubdistro/html/*.html


